[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "ry9cfwalhd00"
  CONTENTFUL_ACCESS_TOKEN = "aVj83fVNOc6PsoPBJybW23u36f3tj2I8StKMBtwdrEQ"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "rXRXj9kb3FmVK5OHO2cU7xQo8tOWk_ndQVbxfluLTag"
